var salesByYear = {
  getData: `SELECT 
              DATENEW, 
              SUM(UNITS) AS ITEMSSOLD, 
              MAX(SUBTOTALSALES) AS LARGESTORDER, 
              SUM(SUBTOTALSALES) AS TOTALSALES, 
              SUM(SUBTOTALTAXCOLLECTED) AS TOTALTAXCOLLECTED, 
              SUM(SUBTOTAL) AS TOTAL 
            FROM  ( 
              SELECT  
                  DATE_FORMAT(RECEIPTS.DATENEW,'%Y') AS DATENEW, 
                  TICKETS.ID, 
                  SUM(TICKETLINES.UNITS) AS UNITS, 
                  SUM(TICKETLINES.PRICE * TICKETLINES.UNITS) AS SUBTOTALSALES, 
                  SUM(TICKETLINES.PRICE * TICKETLINES.UNITS * TAXES.RATE) AS SUBTOTALTAXCOLLECTED, 
                  SUM((TICKETLINES.PRICE+TICKETLINES.PRICE*TAXES.RATE)*TICKETLINES.UNITS) AS SUBTOTAL 
              FROM  
                  TICKETLINES, PRODUCTS, TICKETS, RECEIPTS, TAXES, CATEGORIES 
              WHERE 
                  RECEIPTS.ID = TICKETS.ID 
                  AND TICKETS.ID = TICKETLINES.TICKET 
                  AND TICKETLINES.PRODUCT = PRODUCTS.ID 
                  AND TICKETLINES.TAXID = TAXES.ID  
                  AND TICKETLINES.PRODUCT = PRODUCTS.ID 
                  AND TICKETS.ID = TICKETLINES.TICKET 
                  AND RECEIPTS.ID = TICKETS.ID 
                  AND CATEGORIES.id = PRODUCTS.CATEGORY
                  ***
              GROUP BY DATE_FORMAT(RECEIPTS.DATENEW,'%Y'), TICKETS.ID 
            ) AS SQ 
            GROUP BY DATENEW 
            ORDER BY DATENEW DESC`,
};

module.exports = salesByYear;
